### ISSUE TITLE
"To Do - Add a way to run FL when running this?"

### ISSUE THREAD

**Issue by voxain** [SayakaIsBaka/fls-rich-presence-cs#2]
Just an idea - add the program to windows autostart.
For me, everytime i close fl, the program closes too. Keep it running in the background and let it check when fl starts running, then enable the RP again.

**Comment by SayakaIsBaka** [comment]
I actually thought of doing this, I guess this is doable

Will try to do this when I have time

**Comment by SayakaIsBaka** [comment]
Added this feature, check the last release
